# Generated by Django 5.2.8 on 2025-11-30 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('idade', models.PositiveIntegerField()),
                ('curso', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=50)),
                ('motivo_evasao', models.TextField(blank=True, null=True)),
                ('risco_evasao', models.BooleanField(default=False)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
