# Generated by Django 6.0 on 2025-12-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aluno',
            name='curso',
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='periodo',
        ),
        migrations.AddField(
            model_name='aluno',
            name='serie',
            field=models.CharField(default='Indefinido', max_length=50),
            preserve_default=False,
        ),
    ]
